apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: DATA+OMITTED
      server: https://EB564649D59C8F54A481E5FBFAF8826C.gr7.ap-southeast-1.eks.amazonaws.com
    name: arn:aws:eks:ap-southeast-1:006923918343:cluster/multi-k8s
contexts:
  - context:
      cluster: arn:aws:eks:ap-southeast-1:006923918343:cluster/multi-k8s
      user: arn:aws:eks:ap-southeast-1:006923918343:cluster/multi-k8s
    name: arn:aws:eks:ap-southeast-1:006923918343:cluster/multi-k8s
current-context: arn:aws:eks:ap-southeast-1:006923918343:cluster/multi-k8s
kind: Config
preferences: {}
users:
  - name: arn:aws:eks:ap-southeast-1:006923918343:cluster/multi-k8s
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1alpha1
        args:
          - --region
          - ap-southeast-1
          - eks
          - get-token
          - --cluster-name
          - multi-k8s
        command: aws
        env: null
